Feature/vote 2587 string templates
usagov/vote-gov-drupal pull request #1049
Opened 2024-10-16 05:17 UTC by rayestrada

## Jira ticket

Insert a link to the Jira ticket (e.g VOTE-XXX).

## Description

Insert a brief summary of the changes included in this PR and any additional information or context which may help the reviewer.

## Deployment and testing

### Post-deploy steps

1. Insert any required steps to take before beginning test.

### QA/Testing instructions

1. Insert steps to test and confirm the result meets the "definition of done".

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been included above.
- [ ] No merge conflicts exist with the target branch.
- [ ] Automated tests have passed on this PR.
- [ ] A reviewer has been designated.
- [ ] Deployment and testing steps have been documented above, if applicable.

## Checklist for the Peer Reviewers

- [ ] The file changes are relevant to the task objective.
- [ ] Code is readable and includes appropriate commenting.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps were successfully completed, if applicable.
- [ ] Applicable logs are free of errors.

2024-11-07 17:05 UTC, SamiraMSadat requested changes

2024-11-07 17:05 UTC, SamiraMSadat commented on web/themes/custom/votegov/templates/block/block-content--partnership.html.twig
> +        <a extlinkjs-ignore
There needs to a style for the class that limits the size of the image.

2024-11-07 17:05 UTC, SamiraMSadat commented on web/themes/custom/votegov/templates/block/block-content--partnership.html.twig
> +        <a href="{{ content.field_usagov_logo_link | field_value }}" extlinkjs-ignore>
There needs to be a style for the class that limits the size of the image.

2024-11-13 21:59 UTC, rayestrada commented
I've added new size styles for the imgs. I've also removed the alt text for the U.S.Flag icon and made that decorative following recent updates to the USWDS banner https://designsystem.digital.gov/components/banner/.

2024-11-14 17:02 UTC, SamiraMSadat approved these changes

2024-11-14 17:02 UTC, merged