Vote-3147: RTL style updates
usagov/vote-gov-drupal pull request #1144
Opened 2024-12-02 01:51 UTC by clmedders

## Jira ticket

[Vote-3147](https://cm-jira.usa.gov/browse/VOTE-3147)

## Description

Addressing various RTL style issues:
1. accessibility page had element off to the side causing it to zoom out in mobile 
2. the arrows for quick links were not pointing the right direction 
3. the accessibility bar was going behind the touchpoints form on the accessibility page 

<details>
<summary>Screen shots</summary>
<br>
<img width="1509" alt="Screenshot 2024-12-01 at 8 45 21 PM" src="https://github.com/user-attachments/assets/babdc10d-84c6-4695-a4d9-997dd6afc33c">
<br>
<br>
<img width="1507" alt="Screenshot 2024-12-01 at 8 44 50 PM" src="https://github.com/user-attachments/assets/c674a555-1af9-4e66-82b8-bec819552ff7">
<br>
<br>
<img width="1505" alt="Screenshot 2024-12-01 at 8 44 27 PM" src="https://github.com/user-attachments/assets/32448dbe-210f-4828-91fd-e528461bbfdd">
</details>

## Deployment and testing

### Post-deploy steps

1. cd into the `votegov` theme and run `npm run build`

### QA/Testing instructions

1. switch to the AR translation and verify that the arrows for quick links are pointing the right direction 
2. visit the accessibility page  and ensure that you do not need to scroll over to see the page while in mobile view 
3. while on the accessibility page scroll to the touchpoints form and check that the accessability bar does not go behind the form.

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been included above.
- [ ] No merge conflicts exist with the target branch.
- [ ] Automated tests have passed on this PR.
- [ ] A reviewer has been designated.
- [ ] Deployment and testing steps have been documented above, if applicable.

## Checklist for the Peer Reviewers

- [ ] The file changes are relevant to the task objective.
- [ ] Code is readable and includes appropriate commenting.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps were successfully completed, if applicable.
- [ ] Applicable logs are free of errors.

2024-12-02 01:53 UTC, clmedders commented on web/themes/custom/votegov/src/sass/components/quick-links.scss
> +      background: url('../../img/svg/arrow-white-rtl.svg') no-repeat left center;
i updated the current arrow svg to point left.. and added it to the RTL language

2024-12-02 18:02 UTC, rayestrada requested changes

2024-12-02 18:02 UTC, rayestrada commented on web/themes/custom/votegov/src/sass/uswds-overrides/usa-banner.scss
> +      }
I couldn't find this being used.

2024-12-04 13:54 UTC, clmedders commented on web/themes/custom/votegov/src/sass/components/columns.scss
> -    column-gap: 2rem;
This was messing with the wrapping of the arrow for the quick links.. and when i removed it it did not adjust much so didn't seem like it was needed... let me know if you feel other wise

2024-12-11 20:29 UTC, rayestrada commented
You were right about using a separate svg for rtl. Changing the pseudo element to inline block caused it to break to a new line by itself when the width of the column decreased.

2024-12-11 20:29 UTC, merged