VOTE-975: Delete block_content revisions greater than 10 revisions
usagov/vote-gov-drupal pull request #130
Opened 2023-04-05 13:31 UTC by MakaziMtingwa

## Jira ticket (required)
[VOTE-975](https://bixal-projects.atlassian.net/browse/VOTE-975)

## Description (optional)
Add custom code to remove block_content revisions above 10 revisions per block.

## Deployment and testing (required, if applicable)
### Testing steps
1. Create 10 revisions for a block and run a sql command **SELECT count(*) FROM block_content_revision WHERE id={  block_id }** to be sure future saves/revisions do not exceed 10.
2. Also **SELECT * FROM block_content_revision WHERE id={ block_id } ORDER BY revision_created DESC;** lists the latest revisions left in descending order.

2023-04-06 14:31 UTC, rayestrada requested changes
Makazi please resolve the php linting errors. You can reproduce the lint errors on your local by running the command `lando coder-sniffer`.

2023-04-06 14:43 UTC, MakaziMtingwa commented
Hi @rayestrada I attempted to rerun the pipeline since I'm not receiving any php errors on this feature branch on my local and the pipeline here doesn't show what the error is.  Are you able to re-run the pipeline for this PR?

2023-04-07 13:57 UTC, MakaziMtingwa commented
Hi @rayestrada This is ready to re-review if you haven't already.

2023-04-07 16:24 UTC, rayestrada approved these changes

2023-04-07 16:24 UTC, merged