Vote 801 -> cypress installation
usagov/vote-gov-drupal pull request #14
Opened 2023-01-18 20:08 UTC by clmedders

link to ticket -> https://bixal-projects.atlassian.net/browse/VOTE-801

### Purpose of PR -> this pr will add cypress to vote.gov drupal repo 

### Extra Info on work:

- I created a `testing` folder... in order to move the `cypress.config.js`, `package.json` and `package-lock.json` into the cypress folder it needed an extra one on top of it in order for the tests to work.  I was not able to just add them to the cypress folder and everything still works 
- there is a sample spec file to show that everything is working.. this just simply loads the page and checks that it has loaded, once there is more migrated in this will be removed.
- there will be future configuration needed such as scripts and other tests added but will do that on an as-needed basis. 

### How to test:

1. pull down branch 
2. start local env 
3. cd into `testing` folder 
4. `npm run cy:test` this will run test headless 
5. `npm run cy:open` this will open the cypress runner 

for the last 2 steps ensure that the test is passing as expected

2023-01-18 20:08 UTC, clmedders commented on testing/cypress.config.js
> +});
most of this was brought over from the old vote.gov set up

2023-01-27 00:11 UTC, rayestrada requested changes
Christian can you add a `.nvmrc` file in here to define which version of node. We are using node 18 for the theme. I would suggest using the same version.

2023-01-27 00:11 UTC, rayestrada commented on testing/package.json
> +  "name": "vote-gov-drupal",
update name to `"Vote.gov Cypress testing suite"`

2023-01-27 00:11 UTC, rayestrada commented on testing/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
Can we make `test` script run `cy:test`?

2023-01-27 00:11 UTC, rayestrada commented on testing/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
You might have to reorder the list of scripts.

2023-01-27 14:50 UTC, clmedders commented on testing/.nvmrc
> +18
added file!

2023-01-27 14:51 UTC, clmedders commented on testing/package.json
> +  "name": "vote.gov-cypress-testing-suite",
went to update the name with what you suggested but it yelled at me for format and wanted it in this format

2023-01-27 14:53 UTC, clmedders commented on testing/package.json
> +    "cy:test": "cypress run --spec 'cypress/e2e/tests/**/*'",
so i had a `cy.test` already but i think that one just came with the file when I ran the `npm init` command.  i took out the other `test` in the file but here is the `cy:test` that will run the cypress test headless.

2023-01-27 15:30 UTC, rayestrada approved these changes

2023-01-27 15:32 UTC, merged