Vote 983 -> Translations Url Test
usagov/vote-gov-drupal pull request #174
Opened 2023-05-04 13:52 UTC by clmedders

**_Delete all details that do not apply to this PR!_**

## Jira ticket (required)
[Vote-983](https://bixal-projects.atlassian.net/browse/VOTE-983)

## Description (optional)
This PR will add test coverage to verify that each language option has the correct href path to direct the user to the right URL once it is clicked. 

## Deployment and testing (required, if applicable)
### Testing steps
1. Pull down branch 
2. start local 
3. cd into `testing`
4. run `npm run cy:open`
5. select the `translations-urls.cy.js` file and verify test passes

2023-05-05 17:52 UTC, nehemiah-abuga submitted a review, later dismissed
I have reviewed the changes and the tests passed. Approved

2023-05-05 23:08 UTC, rayestrada requested changes
Also please resolve the merge conflict in this PR.

2023-05-05 23:08 UTC, rayestrada commented on testing/cypress/e2e/tests/translations-urls.cy.js
> +          })
This isn't scalable. If we add another language or change the order this test will break. Can you loop through the list and check to make sure each link returns a 200 instead?

2023-05-08 16:36 UTC, rayestrada approved these changes

2023-05-08 16:36 UTC, merged