Feature/vote 1109/korean state character logic
usagov/vote-gov-drupal pull request #178
Opened 2023-05-05 19:55 UTC by SamiraMSadat

## Jira ticket (required)
https://bixal-projects.atlassian.net/browse/VOTE-1109

## Description (optional)
Rework the Korean state character logic to use translation files

## Deployment and testing (required, if applicable)
### Pre-deploy steps
1. lando retune

### Testing steps
1. Visit http://vote-gov.lndo.site/ko/register/as and verify the state char is not displayed (Korean - territory)
2. Visit http://vote-gov.lndo.site/ko/register/co and verify the state char is displayed (Korean - state)
3. Visit http://vote-gov.lndo.site/register/co and verify that the "state" string does not display (English - state)

2023-05-05 22:54 UTC, rayestrada requested changes

2023-05-05 22:54 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/content/page-title.html.twig
> +{% set title = 'Register to vote in @state_name' | t ({"@state_name": title}) %}
Update this to add in the korean state character
```
{% if node_type == "state_territory" and language == 'ko' and currentnode.field_is_state.value %}
  {% set korean_state_char = "state" | t %}
  {% set title = title ~ " " ~ korean_state_char %}
{% endif %}

{% set title = 'Register to vote in @state_name' | t ({"@state_name": title}) %}
```

2023-05-05 22:54 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/node/node--state-territory--full.html.twig
> +{% endif %}
Simplify this to remove redundancy
```
{% set state_name = label | field_value | render %}

{# Korean 'state' character logic #}
{% if language == 'ko' and node.field_is_state.value %}
  {% set korean_state_char = "state" | t %}
  {% set state_name = state_name ~ " " ~ korean_state_char %}
{% endif %}
```

2023-05-05 22:54 UTC, rayestrada commented on web/modules/custom/vote_utility/translations/ko.po
> +msgstr "버지니아 주에서는 유권자 등록이 필요하지 않습니다.  @state_name 선거국 웹사이트에서 @link를 이용하시기 바랍니다."
Can you run this through google translate or some other tool? I did and it said "Virginia" it it! We may need a bug ticket to fix this.

2023-05-05 22:54 UTC, rayestrada commented on web/modules/custom/vote_utility/translations/ko.po
> +msgstr "버지니아 주에서는 유권자 등록이 필요하지 않습니다.  @state_name 선거국 웹사이트에서 @link를 이용하시기 바랍니다."
Also this may say "...in the state" `주에서는`

2023-05-08 20:53 UTC, SamiraMSadat commented on web/modules/custom/vote_utility/translations/ko.po
> +msgstr "버지니아 주에서는 유권자 등록이 필요하지 않습니다.  @state_name 선거국 웹사이트에서 @link를 이용하시기 바랍니다."
I see the same thing, I will make a bug ticket for this.

2023-05-10 00:31 UTC, rayestrada requested changes

2023-05-10 00:31 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/content/page-title.html.twig
> +{% set title = 'Register to vote in @state_name' | t ({"@state_name": title}) %}
This solution makes all pages prefaced with "Register to vote in".
Let's rewrite our condition to make sure it's only applied on state/territory pages
```
{% if node_type == "state_territory" %}
  {% if language == 'ko' and currentnode.field_is_state.value %}
    {% set korean_state_char = "state" | t %}
    {% set title = title ~ " " ~ korean_state_char %}
  {% endif %}

  {% set title = 'Register to vote in @state_name' | t ({"@state_name": title}) %}
{% endif %}
```

2023-05-10 17:53 UTC, rayestrada approved these changes

2023-05-10 17:54 UTC, merged