Vote-1521 -> link validator test update
usagov/vote-gov-drupal pull request #218
Opened 2023-05-24 15:52 UTC by clmedders

**_Delete all details that do not apply to this PR!_**

## Jira ticket (required)
[Vote-1521](https://bixal-projects.atlassian.net/browse/VOTE-1521)

## Description (optional)
This Pr will update both Link validation tests, External (English and Spanish) and internal links.  Before we were just hitting the home page to migrate the test over.  Now that we have state pages and translations we need to update the test to do the end goal of validating the links 

Please note: there are links that are failing, this will be address in another ticket the goal of this Pr is to just to update the tests to run how they need to be in order to test the way we need them too. 

## Deployment and testing (required, if applicable)
### Testing steps
1. Pull down branch 
2. start local 
3. cd into `testing`
4. run `npm run cy:proofer` and `npm run cy:links` and verify that the tests are running (note failing links will be addressed and ticketed out for further investigation for a path forward)

2023-05-30 17:21 UTC, nehemiah-abuga submitted a review, later dismissed
Tests for Arizona, Connecticut, Hawaii, Ohio, U.S. Virgin Islands. As per Christian's comments, failure are expected

2023-05-30 22:29 UTC, rayestrada requested changes

2023-05-30 22:29 UTC, rayestrada commented on testing/cypress/e2e/externalLinks/spanish-external-links-validator.cy.js
> +  'https://info.scvotes.sc.gov/eng/ovr/start.aspx?ref=voteusa_en'
all these links should have `voteusa_es` parameter value for spanish

2023-06-01 19:16 UTC, rayestrada approved these changes

2023-06-01 19:17 UTC, merged