Vote-925 -> State Registration Drop Down Test
usagov/vote-gov-drupal pull request #223
Opened 2023-05-26 15:22 UTC by clmedders

**_Delete all details that do not apply to this PR!_**

## Jira ticket (required)
[Vote-925](https://bixal-projects.atlassian.net/jira/software/c/projects/VOTE/boards/254?modal=detail&selectedIssue=VOTE-925&assignee=611272e0eb7aef00694b8a97)

## Description (optional)
This PR will add test for the drop-down for state registration.  

> **NOTE**
> This test will click though each option... at the start of the test it will grab the value that is listed in the option.  After that, it will store the value and then click the option.  After it clicks the option it will grab the URL for the page and ensure that the URL contains the value that was stored to make sure that the user went to the correct URL  

## Deployment and testing (required, if applicable)
### Testing steps
1. Pull donw branch 
2. start local 
3. cd into `testing`
4. run `npm run cy:open`
5. select the `state-registration.cy.js` test and verify that is is passing

2023-06-01 15:01 UTC, nehemiah-abuga submitted a review, later dismissed
I am getting redirection error
![image](https://github.com/usagov/vote-gov-drupal/assets/121119072/a59d6fb4-e06d-4386-9362-07233a3862c4)

2023-06-01 16:23 UTC, clmedders commented
@nehemiah-abuga can you pull down the latest... i pushed up a fix for that

2023-06-02 00:05 UTC, rayestrada requested changes

2023-06-02 00:05 UTC, rayestrada commented on testing/cypress/e2e/tests/state-registration.cy.js
> +          cy.url().should('contain', value)
@clmedders can we also test here that the page visit returns a successful response?

2023-06-02 18:42 UTC, rayestrada approved these changes

2023-06-02 18:43 UTC, merged