Bug/vote 1477 untranslated links
usagov/vote-gov-drupal pull request #254
Opened 2023-06-14 19:48 UTC by clmedders

**_Delete all details that do not apply to this PR!_**

## Jira ticket (required)
Insert Jira ticket link

## Description (optional)
Sending Draft for Ray to take a look before adding info... 

## Deployment and testing (required, if applicable)
### Pre-deploy steps
1. Insert step one

### Post-deploy steps
1. Insert step one

### Testing steps
1. Insert step one

2023-06-14 22:19 UTC, rayestrada requested changes

2023-06-14 22:19 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/partial/register/registration-type--online.html.twig
> +      {% if language != "en" and content.field-override-registration-link is empty %}
Update to
`{% if language != "en" and not content.field_override_registration_link | render %}`

2023-06-14 22:19 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/partial/register/registration-type--online.html.twig
> +          {% set registration_link_text = registration_link_text ~ in_english %}
We need to add a space here 
`{% set registration_link_text = registration_link_text ~ ' ' ~ in_english %}`

2023-06-15 14:48 UTC, clmedders commented on web/modules/custom/vote_utility/translations/nv.po
I was not sure about this one but let me know if I didn't not do this one correctly

2023-06-15 19:36 UTC, rayestrada requested changes

2023-06-15 19:36 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/partial/register/registration-type--mail.html.twig
> +          {% set in_english = "(in English)" | t %}
same here

2023-06-15 19:36 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/partial/register/registration-type--mail.html.twig
> +          {% set more_info_link = more_info_link ~ ' ' ~ in_english %}
This should be `more_info_link_text`

2023-06-15 19:36 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/partial/register/registration-type--mail.html.twig
> +          {% set in_english = "(in English)" | t %}
same here

2023-06-15 19:36 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/partial/register/registration-type--online.html.twig
> +
remove extra line space

2023-06-15 19:36 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/partial/register/registration-type--online.html.twig
> +
remove extra line space

2023-06-15 19:36 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/partial/register/registration-type--online.html.twig
> +          {% set in_english = "(in English)" | t %}
same here

2023-06-15 19:36 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/partial/register/registration-type--online.html.twig
> +          {% set in_english = "(in English)" | t %}
same here

2023-06-15 19:36 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/partial/register/registration-type--online.html.twig
> +          {% set in_english = "(in English)" | t %}
same here

2023-06-15 19:36 UTC, rayestrada commented on testing/package-lock.json
Remove this file modification

2023-06-16 13:19 UTC, clmedders commented on web/modules/custom/vote_utility/translations/es.po
removed (in english)

2023-06-16 23:01 UTC, rayestrada approved these changes

2023-06-16 23:03 UTC, merged