Vote-238 -> Set up links validation on schedule
usagov/vote-gov-drupal pull request #354
Opened 2023-08-24 14:56 UTC by clmedders

## Jira ticket

[Vote-238](https://cm-jira.usa.gov/secure/RapidBoard.jspa?rapidView=4046&projectKey=VOTE&view=detail&selectedIssue=VOTE-238&quickFilter=23166)

## Description

This PR will set up both external and internal links on a schedule to run on stage on Monday and Thursday at 9am est.  also sets up that if the first test fails the second one will still run but the pipeline will fail no matter what if any fails 

## Deployment and testing

### Pre-deploy

n/a

### Post-deploy

n/a

### QA/Test

1. Review file changes to ensure that jobs were added correctly and there are there is now a set run for link validation to run on a con (schedule)

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been included above.
- [ ] No merge conflicts exist with the target branch.
- [ ] Automated tests have passed on this PR.
- [ ] A reviewer has been designated.
- [ ] Deployment and testing steps have been documented above, if applicable.
- [ ] The result of these changes meet the JIRA ticket "definition of done".
- [ ] This work meets the project [standards](/usagov/vote-gov-drupal/blob/dev/docs/standards.md).

## Checklist for the Peer Reviewers

- [ ] The code has been reviewed.
- [ ] The file changes are relevant to the task.
- [ ] The author of the commits match the assignee.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps have been successfully completed and the results match "definition of done".
- [ ] Drupal database log and browser console log are free of errors.
- [ ] There are no known side-effects outside the expected behavior.
- [ ] Code is readable and includes appropriate commenting.

2023-08-25 23:11 UTC, rayestrada requested changes

2023-08-28 14:33 UTC, clmedders commented on .circleci/config.yml
> +  link-validation-cron-workflow:
updated

2023-08-28 14:34 UTC, clmedders commented
@rayestrada after looking into it... We have to add a when flag on a repeated step that we would like to run if it does fail.  I have added this flag on the link validation steps, cypress, and the scheduled back up that we talked about.

2023-08-28 19:31 UTC, rayestrada approved these changes

2023-08-28 19:32 UTC, merged