VOTE-854 Apply styling to the header components
usagov/vote-gov-drupal pull request #41
Opened 2023-02-23 20:29 UTC by SamiraMSadat

Delete all details that do not apply to this PR!

Jira ticket (required)
https://bixal-projects.atlassian.net/browse/VOTE-854

Description (optional)
Apply styling to the header region div
Apply styling to the government banner component of the header
Apply styling to the search bar
Apply styling to the language switcher
Apply styling to the site-wide alert

Testing steps
Check out the feature/VOTE-894-header-styling
Run lando retune
View the website in browser and check the following:
a. The default state of the accordion is collapsed
b. The background color is #f0f0f0
c. The images and icons are visible
d. The layout of each component within the header region is correct.

2023-02-27 17:58 UTC, SamiraMSadat commented
To review the site-wide alert, you will need to create two or more side-wide alert blocks within the admin interface so that there are examples to display in the view.

2023-02-28 00:23 UTC, rayestrada requested changes
Please add this to the `src/sass/uswds-overrides/_override-usa-site-alert.scss`

```
.usa-alert__text {
  > * {
    margin: 0;

    + * {
      margin-top: 1rem;
    }
  }
}
```

This will remove the excessive padding above and below the site alert text.

2023-02-28 00:23 UTC, rayestrada commented on web/themes/custom/vote_gov/templates/block/block-content--sitewide-alert.html.twig
> +      <p class="usa-alert__text">
Change this wrapper to a `<div>`

2023-02-28 18:54 UTC, rayestrada approved these changes

2023-02-28 18:56 UTC, merged