Feature/vote 449 add homng translation
usagov/vote-gov-drupal pull request #515
Opened 2024-01-25 15:43 UTC by daniel-crowder

## Jira ticket

Insert a link to the Jira ticket (e.g VOTE-XXX).

## Description

Insert a brief summary of the changes included in this PR and any additional information or context which may help the reviewer.

## Deployment and testing

### Pre-deploy

1. Insert any required steps to take before merging and running post-deploy.

### Post-deploy

1. Insert any required steps to take before beginning test.

### QA/Test

1. Insert steps to test and confirm the result meets the "definition of done".

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been included above.
- [ ] No merge conflicts exist with the target branch.
- [ ] Automated tests have passed on this PR.
- [ ] A reviewer has been designated.
- [ ] Deployment and testing steps have been documented above, if applicable.

## Checklist for the Peer Reviewers

- [ ] The file changes are relevant to the task objective.
- [ ] Code is readable and includes appropriate commenting.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps were successfully completed, if applicable.
- [ ] Applicable logs are free of errors.

2024-01-30 17:24 UTC, rayestrada requested changes

2024-01-30 17:24 UTC, rayestrada commented on config/sync/language/hmn/core.date_format.revision_date.yml
> +pattern: 'n \H\l\i\s \n\t\u\j, \h\n\u\b \t\i\m j, Y'
Change to `pattern: 'd F, Y'`

2024-01-31 15:30 UTC, daniel-crowder commented on web/modules/custom/vote_utility/translations/hmn.po
> +msgstr "General Services Administration"
Correct, I wasn't able to locate a translation for it. Even in the following it wasn't translated.
"Lub website tseeb tiag ntawm (General Services Adminstration)"

2024-02-01 15:32 UTC, rayestrada approved these changes

2024-02-01 15:41 UTC, merged