VOTE-1001 Add global touchpoints feedback survey
usagov/vote-gov-drupal pull request #632
Opened 2024-03-28 17:37 UTC by rayestrada

## Jira ticket

https://cm-jira.usa.gov/browse/VOTE-1001

## Description

This task added a button in the bottom right for a touchpoints survey. On mobile it is at the bottom of the scrollable page. It should trigger a touchpoints form dialog when selected.

## Deployment and testing

### Post-deploy

1. cd into votegov theme and run `npm run build`
2. run `lando drush cr`

### QA/Test

1. Visit http://vote-gov.lndo.site/ and confirm a touchpoint button displays on bottom right on mobile.
2. Click the button and make sure the form dialog displays.

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been included above.
- [ ] No merge conflicts exist with the target branch.
- [ ] Automated tests have passed on this PR.
- [ ] A reviewer has been designated.
- [ ] Deployment and testing steps have been documented above, if applicable.

## Checklist for the Peer Reviewers

- [ ] The file changes are relevant to the task objective.
- [ ] Code is readable and includes appropriate commenting.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps were successfully completed, if applicable.
- [ ] Applicable logs are free of errors.

2024-03-28 20:24 UTC, clmedders commented
<img width="639" alt="Screenshot 2024-03-28 at 4 20 55 PM" src="https://github.com/usagov/vote-gov-drupal/assets/88721460/e411124a-18ce-4a79-85e9-b43706d3d8b3">
saw this when i submitted

2024-03-28 20:26 UTC, clmedders commented
Also, there were several pages, about page, state registration, and state pages that the form was not showing after hitting the button.

2024-03-28 20:26 UTC, clmedders requested changes
see comments above

2024-03-29 17:09 UTC, rayestrada commented
We think the issues are just related to caching and are resolved on refresh. The Form is not expected to work on any host other than vote.gov.

2024-03-29 17:10 UTC, merged