VOTE-2046: Style felony module
usagov/vote-gov-drupal pull request #787
Opened 2024-06-25 20:07 UTC by mlloydbixal

## Jira ticket

[VOTE-2047](https://cm-jira.usa.gov/browse/VOTE-2047)

## Description

Styles felony modules, including high contrast mode.

## Deployment and testing

### Post-deploy steps

1. Iando retune
2. npm run build
3. Navigate to http://vote-gov.lndo.site/voting-after-felony-conviction
4. You may have to edit the page and add content for the modules by selecting "add states double deck card" in the "add basic" dropdown
5. Confirm styles are correct. Figma link: https://www.figma.com/design/u82ICmmHNBKpE1Tw4nsO0K/Vote.gov-Redesign-2024-(Master)?node-id=9061-29360&m=dev
6. Check all screen sizes and high contrast mode

### QA/Testing instructions

1. Insert steps to test and confirm the result meets the "definition of done".

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been included above.
- [ ] No merge conflicts exist with the target branch.
- [ ] Automated tests have passed on this PR.
- [ ] A reviewer has been designated.
- [ ] Deployment and testing steps have been documented above, if applicable.

## Checklist for the Peer Reviewers

- [ ] The file changes are relevant to the task objective.
- [ ] Code is readable and includes appropriate commenting.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps were successfully completed, if applicable.
- [ ] Applicable logs are free of errors.

2024-06-26 13:25 UTC, clmedders commented on web/themes/custom/votegov/src/sass/components/double-deck-card.scss
> +    @include u-padding(4);
looks like there is to much space on the left and right for the bottom text. 


```suggestion
    @include u-padding-x(4);
```

2024-06-26 13:50 UTC, clmedders commented on web/themes/custom/votegov/src/sass/components/double-deck-card.scss
> +    @include u-padding(4);
now that im looking at the figma the mobile and mobile large look to have 2 different spaces on the sides

2024-06-26 13:52 UTC, clmedders commented on web/themes/custom/votegov/src/sass/components/double-deck-card.scss
> +    font-size: 16px;
```suggestion
    font-size: 1rem;
```

2024-06-26 13:55 UTC, clmedders commented on web/themes/custom/votegov/src/sass/components/double-deck-card.scss
> +    text-align: center;
```suggestion
    @include u-text-align('center');
```

2024-06-27 13:40 UTC, clmedders approved these changes

2024-06-27 16:10 UTC, rayestrada requested changes

2024-06-27 16:10 UTC, rayestrada commented on web/themes/custom/votegov/src/sass/components/double-deck-card.scss
> +    font-size: 1rem;
Remove `font-size` let it inherit the global base size.

2024-06-27 19:11 UTC, rayestrada approved these changes

2024-06-27 19:12 UTC, merged