VOTE-2202: add 'homepage' breadcrumb translation
usagov/vote-gov-drupal pull request #794
Opened 2024-06-26 18:43 UTC by mlloydbixal

## Jira ticket

[VOTE-2202](https://cm-jira.usa.gov/browse/VOTE-2202)

## Description

Insert a brief summary of the changes included in this PR and any additional information or context which may help the reviewer.

## Deployment and testing

### Post-deploy steps

1. Insert any required steps to take before beginning test.

### QA/Testing instructions

1. Insert steps to test and confirm the result meets the "definition of done".

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been included above.
- [ ] No merge conflicts exist with the target branch.
- [ ] Automated tests have passed on this PR.
- [ ] A reviewer has been designated.
- [ ] Deployment and testing steps have been documented above, if applicable.

## Checklist for the Peer Reviewers

- [ ] The file changes are relevant to the task objective.
- [ ] Code is readable and includes appropriate commenting.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps were successfully completed, if applicable.
- [ ] Applicable logs are free of errors.

2024-07-02 15:06 UTC, clmedders approved these changes
looks good... tested all the translations

2024-07-02 15:55 UTC, rayestrada requested changes

2024-07-02 15:55 UTC, rayestrada commented on web/themes/custom/votegov/templates/navigation/breadcrumb.html.twig
>            {{ item.text }}
You can remove the `key`. 
The `item.text` is already present we just need to add the `| t` to it.
For both with and without a link add the `t` function like this: `{{ item.text | t }}`.

2024-07-05 22:52 UTC, rayestrada commented on web/themes/custom/votegov/templates/navigation/breadcrumb.html.twig
>            {{ item.text }}
@mlloydbixal this feedback is still pending.

2024-07-09 00:08 UTC, rayestrada approved these changes

2024-07-09 00:13 UTC, merged