Temporary CSS adjustment to in-page nav
usagov/vote-gov-drupal pull request #802
Opened 2024-06-28 17:59 UTC by rkoch2

## Jira ticket

[VOTE-2105](https://cm-jira.usa.gov/browse/VOTE-2105)

## Description

When clicking the name of a section on the USWDS in-page nav component, the "current section" indicator does not move to the correct section. This temporary adjustment hides the current section indicator by removing the text color adjustment and left indicator bar, until the bug can be resolved with USWDS (issue [here](https://github.com/uswds/uswds/issues/5953)).

Before (darker color and left indicator show which section is currently on-screen):
![image](https://github.com/usagov/vote-gov-drupal/assets/78001945/bb92c8b5-f07b-43b2-b643-2da44cb83978)

After change (no visual indication of current section):
![image](https://github.com/usagov/vote-gov-drupal/assets/78001945/da0eaffc-84d0-4cc9-a5d4-0e655bc17fc9)

## Deployment and testing

### Post-deploy steps

Navigate to `web/themes/custom/votegov`, and run `npm run dev`
In the root directory, run `lando retune`

### QA/Testing instructions

1. Navigate to a page where the in-page nav appears -- for example, Guide to Voting > Voting as a college student
2. Make sure that the in-page nav appears on the right side of the page
3. Scroll through the different sections of the page, making sure that there are no visual changes to the in-page nav (ie. changes that would indicate which section of the page is currently on-screen)
4. Interact with the in-page nav by clicking a section name to ensure that it still works as expected (ie. scrolls so that the given section is on-screen)

## Checklist for the Developer

- [x] A link to the JIRA ticket has been included above.
- [x] No merge conflicts exist with the target branch.
- [x] Automated tests have passed on this PR.
- [x] A reviewer has been designated.
- [x] Deployment and testing steps have been documented above, if applicable.

## Checklist for the Peer Reviewers

- [ ] The file changes are relevant to the task objective.
- [ ] Code is readable and includes appropriate commenting.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps were successfully completed, if applicable.
- [ ] Applicable logs are free of errors.

2024-06-29 00:18 UTC, clmedders commented on web/themes/custom/votegov/src/sass/uswds-overrides/usa-in-page-nav.scss
> +      // section indicator (left of current section heading)
i dont think this comment is needed... i would change to something like. "Turning off style untill USWDS fix is made"

2024-06-29 00:19 UTC, clmedders commented on web/themes/custom/votegov/src/sass/uswds-overrides/usa-in-page-nav.scss
> +      // @include vote-link-bg($color: $base-dark);
i would take this line out... just have it as `@include vote-link-bg` and then make a comment above that after the fix to add back `($color: $base-dark)`

2024-06-29 00:20 UTC, clmedders commented on web/themes/custom/votegov/src/sass/uswds-overrides/usa-in-page-nav.scss
>        }
i would use `display: none;` and add it to top of the list, can even comment out the rest to show that it is supposed to be turned off.

2024-06-29 00:21 UTC, clmedders requested changes
see above comments

2024-07-01 16:54 UTC, clmedders approved these changes

2024-07-01 18:05 UTC, rayestrada approved these changes

2024-07-01 18:06 UTC, merged