VOTE-1987: Add custom module to block site_builders on production.
usagov/vote-gov-drupal pull request #975
Opened 2024-09-11 16:15 UTC by daniel-crowder

## Jira ticket

[VOTE-1987](https://cm-jira.usa.gov/browse/VOTE-1987)

## Description

Add custom module to block users who have the site_builder role on production.

## Deployment and testing

### Post-deploy steps

n/a

### QA/Testing instructions

1. Locally enable the Vote Users module.
2. Login as an admin and go to the people admin page.
3. Confirm that users who have the Site Builder role all have a Blocked status.
4. To test a login attempt you can look up the uid of a site builder user and run 'lando drush uli uid={uid}'.
5. Confirm that the response is " Account user.name is blocked and thus cannot login. The user:unblock command may be helpful. "

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been included above.
- [ ] No merge conflicts exist with the target branch.
- [ ] Automated tests have passed on this PR.
- [ ] A reviewer has been designated.
- [ ] Deployment and testing steps have been documented above, if applicable.

## Checklist for the Peer Reviewers

- [ ] The file changes are relevant to the task objective.
- [ ] Code is readable and includes appropriate commenting.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps were successfully completed, if applicable.
- [ ] Applicable logs are free of errors.

2024-09-11 19:27 UTC, rayestrada requested changes

2024-09-11 19:27 UTC, rayestrada commented on web/modules/custom/vote_users/vote_users.install
Can you add an uninstall function to activate users with site_builder role too?

2024-09-13 17:01 UTC, daniel-crowder commented on web/modules/custom/vote_users/vote_users.install
Added

2024-09-13 22:16 UTC, rayestrada approved these changes
This is fantastic!

2024-09-13 22:27 UTC, merged