Vote-2841: Hover style fix - NVRF Links
usagov/vote-gov-drupal pull request #989
Opened 2024-09-16 19:54 UTC by clmedders

## Jira ticket

[Vote-2841](https://cm-jira.usa.gov/browse/VOTE-2841)

## Description

Addressing a hover style for links within the NVRF app.  When links were active there was no contrast between the background and text color 

**Solution** Updated the USWDS override file for `usa-form` and used the same styles from other link hover effects 

Before and After:
<img width="1393" alt="Screenshot 2024-09-16 at 3 34 39 PM" src="https://github.com/user-attachments/assets/42ef18b2-af82-4946-8f62-5f27fc5db9b1">

## Deployment and testing

### Post-deploy steps

1. cd into the `votegov` theme and run `npm run build`

### QA/Testing instructions

1. Start up local an visit a state page and start the digital form 
2. Fill out form and go to the last page for delivery and scroll to the section `A few important notes` and both links `type of identification` and `guide to voting`.  
3. click on the links or use your dom and turn on `:active` state and verity that the correct styles are being applied 

## Checklist for the Developer

- [ ] A link to the JIRA ticket has been included above.
- [ ] No merge conflicts exist with the target branch.
- [ ] Automated tests have passed on this PR.
- [ ] A reviewer has been designated.
- [ ] Deployment and testing steps have been documented above, if applicable.

## Checklist for the Peer Reviewers

- [ ] The file changes are relevant to the task objective.
- [ ] Code is readable and includes appropriate commenting.
- [ ] Code standards and best practices are followed.
- [ ] QA/Test steps were successfully completed, if applicable.
- [ ] Applicable logs are free of errors.

2024-09-18 20:54 UTC, mlloydbixal commented on web/themes/custom/votegov/src/sass/uswds-overrides/usa-form.scss
> +// .usa-form a:where(:not(.usa-button)):active {
Can we remove the commented block?

2024-09-23 22:24 UTC, rayestrada requested changes

2024-09-23 22:24 UTC, rayestrada commented on web/themes/custom/votegov/src/sass/uswds-overrides/usa-form.scss
> +  a:where(:not(.usa-button)):is(:active, :focus) {
@clmedders this seems overcomplicated. Can you identify an existing style that we can update to make sure that the style is applied uniformly?

2024-09-24 21:34 UTC, rayestrada approved these changes

2024-09-24 21:36 UTC, merged